name: Manual Hello World
on:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Worldi
        run: echo "Hello, World!"
      - name: Print Goodby World 
        run: echo "Goodbye, World!"

